### ISSUE TITLE
version of python

### ISSUE THREAD

**Issue by kwignb** [trislaz/gigassl#2]
Hi, thanks for sharing the great works!

Could you please tell me what version of python you are using?

**Comment by trislaz** [comment]
Hello, sure, i'm using python 3.9.12 ! But the code has been tested with python 3.8 too

**Comment by kwignb** [comment]
Thank you for your reply! I ran ```conda install --yes --file requirements.txt``` with Python 3.9.12 as you mentioned and received the message that the following packages are not available.

  - kornia==0.6.4
  - tensorboardx==2.5.1
  - torch==1.11.0
  - openslide_python==1.1.2
  - scikit_image==0.19.2
  - torchvision==0.12.0
  - skimage==0.0
  - staintools==2.1.2
  - scikit_learn==1.2.0

Could you please let me know if there is something wrong?

**Comment by trislaz** [comment]
Thank you for pointing out this malfunction !
I pushed the new requirement file, I tested it on several devices and it seems to work.
Can you please try to run this:
`conda env create -f requirements.yml && conda activate gigassl`
At the root directory of your repo (after pulling it) ?
